version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: eu-central-1

phases:
  install:
    runtime-versions:
        docker: 18
        golang: 1.12
  build:
    commands:
      - aws ecr get-login --no-include-email | sh
      - make REGISTRY_HOST=${REGISTRY_HOST} snapshot
