steps:
  - name: gcr.io/cloud-builders/git
    args: ['fetch', '--tags']
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/bash
    args:
      - -c 
      - git tags ; git describe --long --tags --dirty --always; make REGISTRY_HOST=gcr.io USERNAME=${PROJECT_ID} snapshot
