steps:
  - name: gcr.io/cloud-builders/git
    args: ['init']
  - name: gcr.io/cloud-builders/git
    args: ['fetch']
  - name: gcr.io/cloud-builders/git
    args: ['reset', 'origin/master']
  - name: gcr.io/cloud-builders/docker
    entrypoint: make
    args:
      - REGISTRY_HOST=gcr.io
      - USERNAME=${PROJECT_ID}
      - snapshot
