steps:
  - name: gcr.io/cloud-builders/git
    args: ['fetch', '--tags']
  - name: gcr.io/cloud-builders/docker
    entrypoint: /bin/sh
    args:
      - -x -c 
      - make REGISTRY_HOST=gcr.io USERNAME=${PROJECT_ID} snapshot
